const destinations=[
{id:1,name:"Jaipur",country:"India",cat:["Heritage","Cultural"],img:"https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600",rating:4.7,budget:"$30-80/day",desc:"The Pink City of royal palaces and vibrant bazaars.",places:["Hawa Mahal","Amber Fort","City Palace","Jantar Mantar","Nahargarh Fort"],highlights:["UNESCO World Heritage","Colorful markets","Royal cuisine"]},
{id:2,name:"Goa",country:"India",cat:["Beaches","Adventure"],img:"https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600",rating:4.5,budget:"$25-70/day",desc:"Sun-kissed beaches and vibrant nightlife on India's west coast.",places:["Baga Beach","Fort Aguada","Basilica of Bom Jesus","Dudhsagar Falls","Anjuna Market"],highlights:["Beach parties","Portuguese heritage","Water sports"]},
{id:3,name:"Manali",country:"India",cat:["Mountains","Adventure"],img:"https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600",rating:4.6,budget:"$20-60/day",desc:"Himalayan paradise for adventure seekers and nature lovers.",places:["Rohtang Pass","Solang Valley","Old Manali","Hadimba Temple","Jogini Falls"],highlights:["Skiing","River rafting","Mountain treks"]},
{id:4,name:"Kerala",country:"India",cat:["Beaches","Cultural","Luxury"],img:"https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600",rating:4.8,budget:"$35-100/day",desc:"God's Own Country with serene backwaters and lush greenery.",places:["Alleppey Backwaters","Munnar","Fort Kochi","Periyar Wildlife","Varkala Beach"],highlights:["Houseboat stays","Ayurveda spas","Tea plantations"]},
{id:5,name:"Varanasi",country:"India",cat:["Heritage","Cultural"],img:"https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=600",rating:4.4,budget:"$15-40/day",desc:"The spiritual capital of India on the banks of the Ganges.",places:["Dashashwamedh Ghat","Kashi Vishwanath","Sarnath","Assi Ghat","Ramnagar Fort"],highlights:["Ganga Aarti","Ancient temples","Silk weaving"]},
{id:6,name:"Udaipur",country:"India",cat:["Heritage","Luxury"],img:"images/udaipur.png",rating:4.7,budget:"$30-90/day",desc:"City of Lakes with floating palaces and romantic sunsets.",places:["Lake Pichola","City Palace","Jag Mandir","Saheliyon ki Bari","Monsoon Palace"],highlights:["Lake palaces","Royal heritage","Mewar cuisine"]},
{id:7,name:"Leh-Ladakh",country:"India",cat:["Mountains","Adventure"],img:"https://images.unsplash.com/photo-1626015365107-4cdfb620825e?w=600",rating:4.9,budget:"$25-70/day",desc:"The roof of the world with dramatic landscapes and Buddhist monasteries.",places:["Pangong Lake","Nubra Valley","Magnetic Hill","Thiksey Monastery","Khardung La"],highlights:["Highest motorable roads","Stargazing","Buddhist culture"]},
{id:8,name:"Andaman Islands",country:"India",cat:["Beaches","Adventure"],img:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600",rating:4.6,budget:"$40-100/day",desc:"Pristine beaches and crystal-clear waters in the Bay of Bengal.",places:["Radhanagar Beach","Cellular Jail","Ross Island","Baratang","Neil Island"],highlights:["Scuba diving","Bioluminescent beaches","Coral reefs"]},
{id:9,name:"Rishikesh",country:"India",cat:["Adventure","Cultural"],img:"https://images.unsplash.com/photo-1600011689032-8b628b8a8747?w=600",rating:4.5,budget:"$15-45/day",desc:"Yoga capital of the world nestled in the Himalayan foothills.",places:["Laxman Jhula","Triveni Ghat","Beatles Ashram","Neelkanth Temple","Rajaji Park"],highlights:["White water rafting","Yoga retreats","Bungee jumping"]},
{id:10,name:"Agra",country:"India",cat:["Heritage","Cultural","Budget"],img:"https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600",rating:4.6,budget:"$15-40/day",desc:"Home to the iconic Taj Mahal and Mughal architectural wonders.",places:["Taj Mahal","Agra Fort","Fatehpur Sikri","Mehtab Bagh","Itimad-ud-Daulah"],highlights:["Taj Mahal sunrise","Mughal history","Marble crafts"]},
{id:11,name:"Paris",country:"France",cat:["International","Heritage","Luxury"],img:"https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600",rating:4.8,budget:"$100-300/day",desc:"The City of Light with iconic landmarks and world-class cuisine.",places:["Eiffel Tower","Louvre Museum","Notre-Dame","Montmartre","Champs-Élysées"],highlights:["Art museums","French cuisine","Seine River cruises"]},
{id:12,name:"Bali",country:"Indonesia",cat:["International","Beaches","Cultural"],img:"https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600",rating:4.7,budget:"$30-80/day",desc:"Island of Gods with stunning temples, rice terraces and beaches.",places:["Uluwatu Temple","Tegallalang Terraces","Seminyak","Ubud","Tanah Lot"],highlights:["Temple ceremonies","Surf culture","Rice paddy walks"]},
{id:13,name:"Tokyo",country:"Japan",cat:["International","Cultural","Luxury"],img:"https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600",rating:4.8,budget:"$80-200/day",desc:"Ultra-modern city blending cutting-edge tech with ancient tradition.",places:["Shibuya Crossing","Senso-ji","Akihabara","Meiji Shrine","Tsukiji Market"],highlights:["Cherry blossoms","Sushi culture","Anime districts"]},
{id:14,name:"Santorini",country:"Greece",cat:["International","Beaches","Luxury"],img:"https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=600",rating:4.9,budget:"$100-350/day",desc:"Iconic blue domes and breathtaking sunsets over the Aegean Sea.",places:["Oia","Fira","Red Beach","Akrotiri","Kamari Beach"],highlights:["Caldera views","Wine tasting","Volcanic beaches"]},
{id:15,name:"Dubai",country:"UAE",cat:["International","Luxury","Adventure"],img:"https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600",rating:4.6,budget:"$80-400/day",desc:"Futuristic skyline meets golden deserts and luxury shopping.",places:["Burj Khalifa","Palm Jumeirah","Dubai Mall","Desert Safari","Dubai Marina"],highlights:["Skyscraper views","Desert adventures","Gold souks"]},
{id:16,name:"New York",country:"USA",cat:["International","Cultural","Luxury"],img:"https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600",rating:4.7,budget:"$120-400/day",desc:"The city that never sleeps with iconic skyline and Broadway.",places:["Times Square","Central Park","Statue of Liberty","Brooklyn Bridge","Met Museum"],highlights:["Broadway shows","World cuisine","Iconic skyline"]},
{id:17,name:"Maldives",country:"Maldives",cat:["International","Beaches","Luxury"],img:"https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=600",rating:4.9,budget:"$150-800/day",desc:"Paradise islands with overwater villas and turquoise lagoons.",places:["Male","Maafushi","Vaadhoo Island","Banana Reef","Hulhumale"],highlights:["Overwater bungalows","Snorkeling","Bioluminescent beach"]},
{id:18,name:"Rome",country:"Italy",cat:["International","Heritage","Cultural"],img:"https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600",rating:4.7,budget:"$70-200/day",desc:"Eternal City where ancient ruins meet Renaissance masterpieces.",places:["Colosseum","Vatican","Trevi Fountain","Pantheon","Spanish Steps"],highlights:["Ancient history","Italian cuisine","Art galleries"]},
{id:19,name:"Bangkok",country:"Thailand",cat:["International","Cultural","Budget"],img:"https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600",rating:4.5,budget:"$20-60/day",desc:"Vibrant street life, ornate temples and legendary street food.",places:["Grand Palace","Wat Arun","Chatuchak Market","Khao San Road","Chinatown"],highlights:["Street food","Temple tours","Floating markets"]},
{id:20,name:"Swiss Alps",country:"Switzerland",cat:["International","Mountains","Luxury"],img:"https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=600",rating:4.9,budget:"$150-500/day",desc:"Majestic peaks, pristine lakes and charming alpine villages.",places:["Jungfrau","Zermatt","Interlaken","Lake Geneva","Lucerne"],highlights:["Skiing","Scenic trains","Chocolate tours"]},
{id:21,name:"Darjeeling",country:"India",cat:["Mountains","Cultural","Budget"],img:"https://images.unsplash.com/photo-1622308644420-b20142bd945c?w=600",rating:4.5,budget:"$15-40/day",desc:"Queen of the Hills with tea gardens and Himalayan views.",places:["Tiger Hill","Batasia Loop","Tea Gardens","Peace Pagoda","Toy Train"],highlights:["Tea tasting","Toy train ride","Kanchenjunga views"]},
{id:22,name:"Hampi",country:"India",cat:["Heritage","Budget"],img:"https://images.unsplash.com/photo-1600100397608-e4b1874e2abb?w=600",rating:4.6,budget:"$10-30/day",desc:"Ancient Vijayanagara ruins amidst surreal boulder landscapes.",places:["Virupaksha Temple","Vittala Temple","Elephant Stables","Matanga Hill","Lotus Mahal"],highlights:["UNESCO ruins","Boulder climbing","Coracle rides"]},
{id:23,name:"Shimla",country:"India",cat:["Mountains","Heritage","Budget"],img:"https://images.unsplash.com/photo-1597074866923-dc0589150458?w=600",rating:4.4,budget:"$20-50/day",desc:"Colonial hill station with stunning mountain panoramas.",places:["Mall Road","Christ Church","Jakhoo Temple","Kufri","Toy Train"],highlights:["Colonial architecture","Snow in winter","Scenic walks"]},
{id:24,name:"Ranthambore",country:"India",cat:["Adventure","Budget"],img:"https://images.unsplash.com/photo-1535338454528-1b7e4b131043?w=600",rating:4.5,budget:"$30-80/day",desc:"Tiger territory with ancient forts in Rajasthan's wilderness.",places:["Ranthambore Fort","Zone 3-5","Padam Talao","Jogi Mahal","Surwal Lake"],highlights:["Tiger safaris","Bird watching","Fort exploration"]},
{id:25,name:"Coorg",country:"India",cat:["Mountains","Cultural"],img:"https://images.unsplash.com/photo-1606918801925-e2c914c4b503?w=600",rating:4.5,budget:"$20-60/day",desc:"Scotland of India with coffee plantations and misty hills.",places:["Abbey Falls","Raja's Seat","Dubare Camp","Talacauvery","Namdroling"],highlights:["Coffee tours","Elephant camps","Misty mornings"]},
{id:26,name:"Jaisalmer",country:"India",cat:["Heritage","Adventure","Budget"],img:"https://images.unsplash.com/photo-1609766856923-7e0a0c06e45b?w=600",rating:4.6,budget:"$15-45/day",desc:"Golden city rising from the Thar Desert sands.",places:["Jaisalmer Fort","Sam Dunes","Patwon Haveli","Gadisar Lake","Desert Camp"],highlights:["Desert camping","Camel safari","Golden fort"]},
{id:27,name:"Ooty",country:"India",cat:["Mountains","Budget"],img:"https://images.unsplash.com/photo-1609920658906-8223bd289001?w=600",rating:4.3,budget:"$15-40/day",desc:"Queen of Hill Stations in the Nilgiri Mountains.",places:["Botanical Garden","Ooty Lake","Doddabetta Peak","Tea Factory","Toy Train"],highlights:["Tea estates","Nilgiri railway","Botanical gardens"]},
{id:28,name:"Amritsar",country:"India",cat:["Heritage","Cultural","Budget"],img:"https://images.unsplash.com/photo-1609947017136-9daf32a5eb01?w=600",rating:4.7,budget:"$10-35/day",desc:"Spiritual city home to the magnificent Golden Temple.",places:["Golden Temple","Wagah Border","Jallianwala Bagh","Partition Museum","Hall Bazaar"],highlights:["Golden Temple","Wagah ceremony","Punjabi cuisine"]},
{id:29,name:"Mysore",country:"India",cat:["Heritage","Cultural","Budget"],img:"https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600",rating:4.5,budget:"$15-40/day",desc:"City of Palaces with royal heritage and sandalwood.",places:["Mysore Palace","Chamundi Hills","Brindavan Gardens","St Philomena","Devaraja Market"],highlights:["Dasara festival","Palace illumination","Silk shopping"]},
{id:30,name:"Meghalaya",country:"India",cat:["Mountains","Adventure"],img:"https://images.unsplash.com/photo-1598091383021-15ddea10925d?w=600",rating:4.7,budget:"$20-55/day",desc:"Abode of Clouds with living root bridges and waterfalls.",places:["Living Root Bridges","Dawki River","Mawsynram","Elephant Falls","Shillong Peak"],highlights:["Root bridges","Cleanest village","Crystal rivers"]},
{id:31,name:"London",country:"UK",cat:["International","Heritage","Cultural"],img:"https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=600",rating:4.7,budget:"$100-300/day",desc:"Historic capital blending royal tradition with modern culture.",places:["Big Ben","Tower of London","British Museum","Buckingham Palace","Hyde Park"],highlights:["Royal palaces","West End theatre","Afternoon tea"]},
{id:32,name:"Barcelona",country:"Spain",cat:["International","Beaches","Cultural"],img:"https://images.unsplash.com/photo-1583422409516-2895a77efded?w=600",rating:4.7,budget:"$60-180/day",desc:"Gaudí's masterpiece city on the Mediterranean coast.",places:["Sagrada Familia","Park Güell","La Rambla","Gothic Quarter","Camp Nou"],highlights:["Gaudí architecture","Tapas culture","Beach life"]},
{id:33,name:"Machu Picchu",country:"Peru",cat:["International","Heritage","Adventure"],img:"https://images.unsplash.com/photo-1526392060635-9d6019884377?w=600",rating:4.9,budget:"$40-120/day",desc:"Lost city of the Incas perched high in the Andes.",places:["Sun Gate","Huayna Picchu","Temple of Sun","Inca Trail","Sacred Valley"],highlights:["Inca ruins","Mountain trekking","Andean culture"]},
{id:34,name:"Cape Town",country:"South Africa",cat:["International","Adventure","Beaches"],img:"https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=600",rating:4.6,budget:"$40-130/day",desc:"Where mountains meet ocean in a stunning natural setting.",places:["Table Mountain","Cape Point","Robben Island","V&A Waterfront","Boulders Beach"],highlights:["Table Mountain","Penguin colony","Wine lands"]},
{id:35,name:"Istanbul",country:"Turkey",cat:["International","Heritage","Cultural"],img:"https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=600",rating:4.6,budget:"$30-90/day",desc:"Crossroads of continents where East meets West.",places:["Hagia Sophia","Blue Mosque","Grand Bazaar","Topkapi Palace","Bosphorus"],highlights:["Ottoman heritage","Bazaar shopping","Turkish cuisine"]},
{id:36,name:"Sydney",country:"Australia",cat:["International","Beaches","Luxury"],img:"https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=600",rating:4.7,budget:"$80-250/day",desc:"Harbour city with iconic opera house and golden beaches.",places:["Opera House","Harbour Bridge","Bondi Beach","Taronga Zoo","Blue Mountains"],highlights:["Opera House","Beach culture","Coastal walks"]},
{id:37,name:"Marrakech",country:"Morocco",cat:["International","Cultural","Budget"],img:"https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=600",rating:4.5,budget:"$25-70/day",desc:"Vibrant medina city with colorful souks and riads.",places:["Jemaa el-Fnaa","Majorelle Garden","Bahia Palace","Medina Souks","Koutoubia"],highlights:["Souks shopping","Riad stays","Sahara trips"]},
{id:38,name:"Reykjavik",country:"Iceland",cat:["International","Adventure","Mountains"],img:"https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=600",rating:4.7,budget:"$100-300/day",desc:"Gateway to Northern Lights and dramatic volcanic landscapes.",places:["Blue Lagoon","Golden Circle","Hallgrímskirkja","Thingvellir","Gullfoss"],highlights:["Northern Lights","Geysers","Glacier hikes"]},
{id:39,name:"Kyoto",country:"Japan",cat:["International","Heritage","Cultural"],img:"https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600",rating:4.8,budget:"$70-200/day",desc:"Ancient imperial capital with thousands of temples and shrines.",places:["Fushimi Inari","Kinkaku-ji","Arashiyama","Gion District","Nijo Castle"],highlights:["Geisha culture","Bamboo forest","Tea ceremonies"]},
{id:40,name:"Petra",country:"Jordan",cat:["International","Heritage","Adventure"],img:"https://images.unsplash.com/photo-1579606032821-4e6161c81f13?w=600",rating:4.8,budget:"$40-120/day",desc:"Rose-red city carved into desert cliffs by ancient Nabataeans.",places:["Treasury","Monastery","Siq","Royal Tombs","High Place"],highlights:["Rock-cut architecture","Desert camping","Bedouin culture"]},
{id:41,name:"Vietnam",country:"Vietnam",cat:["International","Cultural","Budget"],img:"https://images.unsplash.com/photo-1528127269322-539801943592?w=600",rating:4.6,budget:"$15-50/day",desc:"From Ha Long Bay to bustling Saigon, a land of contrasts.",places:["Ha Long Bay","Hoi An","Sapa","Cu Chi Tunnels","Mekong Delta"],highlights:["Street food","Boat cruises","Rice terraces"]},
{id:42,name:"Amsterdam",country:"Netherlands",cat:["International","Cultural","Heritage"],img:"https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=600",rating:4.6,budget:"$70-200/day",desc:"Canal-laced city of art, cycling and Dutch golden age charm.",places:["Anne Frank House","Rijksmuseum","Vondelpark","Canal Cruise","Dam Square"],highlights:["Canal cruises","Van Gogh Museum","Cycling culture"]},
{id:43,name:"Cusco",country:"Peru",cat:["International","Heritage","Adventure","Budget"],img:"https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=600",rating:4.5,budget:"$20-60/day",desc:"Ancient Inca capital high in the Peruvian Andes.",places:["Plaza de Armas","Sacsayhuaman","San Pedro Market","Rainbow Mountain","Moray"],highlights:["Inca history","Altitude adventure","Local markets"]},
{id:44,name:"Zanzibar",country:"Tanzania",cat:["International","Beaches","Cultural"],img:"https://images.unsplash.com/photo-1586861203927-800a5acdcc4d?w=600",rating:4.5,budget:"$30-100/day",desc:"Spice island paradise with white sand and turquoise waters.",places:["Stone Town","Nungwi Beach","Prison Island","Spice Tour","Jozani Forest"],highlights:["Spice tours","Dhow cruises","Snorkeling"]},
{id:45,name:"Prague",country:"Czech Republic",cat:["International","Heritage","Budget"],img:"https://images.unsplash.com/photo-1541849546-216549ae216d?w=600",rating:4.6,budget:"$40-100/day",desc:"Fairy-tale city with Gothic spires and cobblestone streets.",places:["Charles Bridge","Prague Castle","Old Town Square","St Vitus","Lennon Wall"],highlights:["Gothic architecture","Craft beer","Night walks"]},
{id:46,name:"Singapore",country:"Singapore",cat:["International","Luxury","Cultural"],img:"https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=600",rating:4.7,budget:"$60-200/day",desc:"Garden city-state with futuristic architecture and hawker food.",places:["Marina Bay Sands","Gardens by the Bay","Sentosa","Chinatown","Orchard Road"],highlights:["Hawker food","Futuristic gardens","Shopping"]},
{id:47,name:"Cairo",country:"Egypt",cat:["International","Heritage","Cultural","Budget"],img:"https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=600",rating:4.5,budget:"$20-60/day",desc:"Land of Pharaohs with pyramids and ancient treasures.",places:["Pyramids of Giza","Sphinx","Egyptian Museum","Khan el-Khalili","Nile Cruise"],highlights:["Pyramids","Nile cruises","Ancient history"]},
{id:48,name:"Lisbon",country:"Portugal",cat:["International","Cultural","Beaches","Budget"],img:"https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=600",rating:4.6,budget:"$40-120/day",desc:"Sun-drenched hills with pastel buildings and tram rides.",places:["Belém Tower","Alfama","Tram 28","Time Out Market","Sintra"],highlights:["Pastéis de nata","Fado music","Tram rides"]},
{id:49,name:"Srinagar",country:"India",cat:["Mountains","Luxury","Cultural"],img:"https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=600",rating:4.6,budget:"$25-70/day",desc:"Paradise on Earth with dal lakes and floating gardens.",places:["Dal Lake","Mughal Gardens","Shankaracharya","Gulmarg","Pahalgam"],highlights:["Houseboat stays","Shikara rides","Saffron fields"]},
{id:50,name:"Pushkar",country:"India",cat:["Heritage","Cultural","Budget"],img:"https://images.unsplash.com/photo-1548013146-72479768bada?w=600",rating:4.3,budget:"$10-30/day",desc:"Sacred town with a holy lake and famous camel fair.",places:["Brahma Temple","Pushkar Lake","Savitri Temple","Camel Fair","Rose Garden"],highlights:["Camel fair","Sacred lake","Desert vibes"]},
{id:51,name:"Hanoi",country:"Vietnam",cat:["International","Cultural","Budget"],img:"https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=600",rating:4.5,budget:"$15-45/day",desc:"Charming capital with ancient temples and vibrant street life.",places:["Old Quarter","Hoan Kiem Lake","Temple of Literature","Ho Chi Minh","Train Street"],highlights:["Pho noodles","Old Quarter walks","Water puppets"]},
{id:52,name:"Queenstown",country:"New Zealand",cat:["International","Adventure","Mountains"],img:"https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=600",rating:4.8,budget:"$80-250/day",desc:"Adventure capital of the world set among dramatic peaks.",places:["Milford Sound","Bungee Jump","Remarkables","Lake Wakatipu","Skyline Gondola"],highlights:["Bungee jumping","Milford Sound","Jet boating"]},
{id:53,name:"Amalfi Coast",country:"Italy",cat:["International","Beaches","Luxury"],img:"https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600",rating:4.8,budget:"$80-300/day",desc:"Dramatic clifftop villages cascading to azure Mediterranean waters.",places:["Positano","Ravello","Amalfi Cathedral","Path of Gods","Capri"],highlights:["Cliffside villages","Limoncello","Boat tours"]},
{id:54,name:"Phuket",country:"Thailand",cat:["International","Beaches","Budget"],img:"https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=600",rating:4.4,budget:"$20-70/day",desc:"Thailand's largest island with stunning beaches and nightlife.",places:["Patong Beach","Phi Phi Islands","Big Buddha","Old Phuket","James Bond Island"],highlights:["Island hopping","Thai massage","Night markets"]},
{id:55,name:"Havana",country:"Cuba",cat:["International","Cultural","Budget"],img:"https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=600",rating:4.4,budget:"$25-70/day",desc:"Time-capsule city with vintage cars and salsa rhythms.",places:["Old Havana","Malecón","El Capitolio","Plaza Vieja","Fusterlandia"],highlights:["Classic cars","Salsa dancing","Cigar culture"]},
{id:56,name:"Patagonia",country:"Argentina",cat:["International","Adventure","Mountains"],img:"https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600",rating:4.8,budget:"$50-150/day",desc:"Untamed wilderness of glaciers, peaks, and vast steppe.",places:["Perito Moreno","Torres del Paine","El Chaltén","Tierra del Fuego","Lake District"],highlights:["Glacier trekking","Wildlife","Rugged landscapes"]},
{id:57,name:"Dubrovnik",country:"Croatia",cat:["International","Heritage","Beaches"],img:"https://images.unsplash.com/photo-1555990793-da11153b2473?w=600",rating:4.6,budget:"$50-150/day",desc:"Pearl of the Adriatic with medieval walls and crystal seas.",places:["Old Town Walls","Lokrum Island","Stradun","Fort Lovrijenac","Cable Car"],highlights:["Game of Thrones","Walled city","Island trips"]},
{id:58,name:"Bhutan",country:"Bhutan",cat:["International","Mountains","Cultural"],img:"https://images.unsplash.com/photo-1553856622-d1b352e9a211?w=600",rating:4.7,budget:"$200-350/day",desc:"Last Shangri-La with stunning dzongs and Gross National Happiness.",places:["Tiger's Nest","Punakha Dzong","Thimphu","Paro Valley","Dochula Pass"],highlights:["Tiger's Nest trek","Buddhist monasteries","Archery"]},
{id:59,name:"Spiti Valley",country:"India",cat:["Mountains","Adventure","Budget"],img:"https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?w=600",rating:4.7,budget:"$15-40/day",desc:"Cold desert with ancient monasteries and stark beauty.",places:["Key Monastery","Chandratal Lake","Kunzum Pass","Dhankar","Pin Valley"],highlights:["Stargazing","Ancient monasteries","High passes"]},
{id:60,name:"Pondicherry",country:"India",cat:["Beaches","Heritage","Cultural","Budget"],img:"https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600",rating:4.4,budget:"$15-45/day",desc:"French colonial charm meets Tamil culture by the Bay of Bengal.",places:["Promenade Beach","Auroville","French Quarter","Paradise Beach","Basilica"],highlights:["French architecture","Auroville","Seaside cafes"]},
{id:61,name:"Gangtok",country:"India",cat:["Mountains","Adventure","Cultural"],img:"https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600",rating:4.6,budget:"$20-55/day",desc:"Himalayan state with rhododendrons and views of Kanchenjunga.",places:["Tsomgo Lake","Nathula Pass","Pelling","Gangtok","Rumtek Monastery"],highlights:["Kanchenjunga views","Buddhist monasteries","Momos"]},
{id:62,name:"Fiji",country:"Fiji",cat:["International","Beaches","Luxury","Adventure"],img:"https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=600",rating:4.6,budget:"$60-250/day",desc:"South Pacific paradise with coral reefs and warm hospitality.",places:["Mamanuca Islands","Coral Coast","Sabeto Hot Springs","Garden of Sleeping Giant","Navua River"],highlights:["Reef snorkeling","Island hopping","Kava ceremonies"]}
,
{id:63,name:"Auli",country:"India",cat:["Mountains","Adventure","Budget"],img:"https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=600",rating:4.5,budget:"$20-50/day",desc:"Skiing paradise in the Garhwal Himalayas with stunning oak forests.",places:["Auli Ropeway","Gorson Bugyal","Kuari Pass","Joshimath","Nanda Devi"],highlights:["Skiing","Meadow treks","Mountain views"]},
{id:64,name:"Varkala",country:"India",cat:["Beaches","Budget"],img:"https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600",rating:4.4,budget:"$15-40/day",desc:"Cliff-top beaches and mineral springs on Kerala's coast.",places:["Varkala Beach","Janardanaswamy Temple","Papanasam Beach","Edava Beach","Anjengo Fort"],highlights:["Cliff beaches","Ayurveda","Surfing"]},
{id:65,name:"Kovalam",country:"India",cat:["Beaches","Budget"],img:"https://images.unsplash.com/photo-1471922694854-ff1b63b20054?w=600",rating:4.3,budget:"$15-45/day",desc:"Crescent-shaped beaches with lighthouse views in Kerala.",places:["Lighthouse Beach","Hawa Beach","Samudra Beach","Vizhinjam Mosque","Halcyon Castle"],highlights:["Lighthouse","Beach resorts","Seafood"]}
];

const regionMap={
1:"Rajasthan",2:"",3:"Himachal Pradesh",4:"",5:"Uttar Pradesh",6:"Rajasthan",
7:"J&K",8:"",9:"Uttarakhand",10:"Uttar Pradesh",
21:"West Bengal",22:"Karnataka",23:"Himachal Pradesh",24:"Rajasthan",25:"Karnataka",
26:"Rajasthan",27:"Tamil Nadu",28:"Punjab",29:"Karnataka",30:"",
49:"J&K",50:"Rajasthan",59:"Himachal Pradesh",60:"",61:"Sikkim",
63:"Uttarakhand",64:"Kerala",65:"Kerala"
};

function getDestLabel(d){
  const r=regionMap[d.id];
  if(d.country!=='India') return d.name;
  return r ? d.name+', '+r : d.name;
}

const budgetOptions=[
  {value:"budget",label:"Budget – Under ₹25,000/person",range:"Under ₹25,000"},
  {value:"midrange",label:"Mid-range – ₹50,000–₹1,50,000/person",range:"₹50,000 – ₹1,50,000"},
  {value:"luxury",label:"Luxury – ₹2,00,000+/person",range:"₹2,00,000+"}
];

const travelStyles=[
  "Adventure & Nature","Cultural & Heritage","Relaxation & Wellness",
  "Family & Kids","Romantic & Honeymoon","Backpacking & Solo"
];

const styleActivities={
  "Adventure & Nature":[
    {m:"🏔 Morning hike & sunrise views",e:"🏕 Camping setup & bonfire dinner"},
    {m:"🏄 Extreme sports session",e:"🌊 River adventure & local cuisine"},
    {m:"🌿 Nature trail & wildlife spotting",e:"🔭 Camp cooking & stargazing"}
  ],
  "Cultural & Heritage":[
    {m:"🏛 Temple visit & heritage walk",e:"🎭 Cultural performance & local dinner"},
    {m:"🖼 Museum tour & art gallery",e:"🍜 Traditional street food crawl"},
    {m:"🎨 Traditional craft workshop",e:"📖 Historical walking tour & storytelling"}
  ],
  "Relaxation & Wellness":[
    {m:"🧘 Spa session & yoga class",e:"🌅 Sunset viewing & fine dining"},
    {m:"🏖 Beach walk & meditation",e:"🍷 Poolside relaxation & local cuisine"},
    {m:"🌺 Nature walk & garden visit",e:"🛶 Sunset cruise & spa treatment"}
  ],
  "Family & Kids":[
    {m:"🎢 Theme park & kids activities",e:"🍕 Family dinner & local market"},
    {m:"🐘 Zoo & aquarium visit",e:"🌙 Night safari & storytelling"},
    {m:"🏖 Beach games & swimming",e:"🎪 Cultural show & snacks"}
  ],
  "Romantic & Honeymoon":[
    {m:"💆 Couples spa & brunch",e:"🕯 Candlelight dinner & sunset"},
    {m:"🚗 Scenic drive & photography",e:"🛶 Boat ride & stargazing"},
    {m:"🛍 Private tour & shopping",e:"🎵 Live music & rooftop dining"}
  ],
  "Backpacking & Solo":[
    {m:"🎒 Local market exploration",e:"🍻 Street food crawl & pub hopping"},
    {m:"🗺 Self-guided walking tour",e:"🌄 Local meetup & sunset point"},
    {m:"🥾 Hostel networking & hike",e:"🌃 Night market & journaling"}
  ]
};
